# Generated by Django 3.1.1 on 2020-09-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200903_1225'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(check=models.Q(name__in=['DEV', 'TRA']), name='valid_name_value'),
        ),
    ]
