# Generated by Django 3.1.1 on 2020-09-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_translationline_instance'),
        ('projects', '0008_project_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='template_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_where_template', to='translations.translationfile'),
        ),
    ]
