# Generated by Django 3.1.1 on 2020-10-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201007_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='template_file',
        ),
    ]
