# Generated by Django 3.1.1 on 2020-09-08 13:32

from django.db import migrations, models
import django.db.models.deletion
import translations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_auto_20200904_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_translation_file', models.BooleanField()),
                ('in_template_file', models.BooleanField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_lines', to='translations.translationblock')),
                ('line_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_lines', to='translations.linetype')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('is_template', models.BooleanField(default=False)),
                ('translated_language', models.CharField(max_length=40, null=True)),
                ('original_file', models.FileField(upload_to=translations.models.TranslationFile.get_file_location)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranlation_files', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='translationblock',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_blocks', to='translations.translationfile'),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='translations.instancetype')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_childs', to='translations.instance')),
            ],
        ),
    ]
