# Generated by Django 3.1.1 on 2020-09-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationline',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='translations.instance'),
        ),
    ]
