# Generated by Django 3.1.1 on 2020-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_auto_20200910_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancetype',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
