# Generated by Django 3.1.1 on 2020-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_auto_20200910_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationline',
            name='in_template_file',
            field=models.BooleanField(null=True),
        ),
    ]
