# Generated by Django 3.1.1 on 2020-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_auto_20200916_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationfile',
            name='translated_language',
            field=models.CharField(choices=[('fr', 'Français'), ('ndlr', 'Néerlandais')], max_length=40, null=True),
        ),
    ]
