# Generated by Django 3.1.1 on 2020-11-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_template_file'),
        ('translations', '0007_auto_20201016_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationblock',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationblock',
            name='raw_text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translationblock',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translationfile',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='translationfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_files', to='projects.project'),
        ),
    ]
