# Generated by Django 3.1.1 on 2020-11-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_template_file'),
        ('translations', '0008_auto_20201113_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='projects.project'),
            preserve_default=False,
        ),
    ]
