# Generated by Django 3.1.1 on 2021-01-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_template_file'),
        ('translations', '0010_auto_20210115_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('type', models.CharField(choices=[('model', 'Model')], max_length=40)),
                ('file', models.FileField(upload_to='get_file_location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='projects.project')),
            ],
        ),
    ]
