# Generated by Django 3.1.1 on 2021-01-22 12:12

from django.db import migrations, models
import translations.models.config_file


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0011_configfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='file',
            field=models.FileField(upload_to=translations.models.config_file.ConfigFile.get_file_location),
        ),
        migrations.AlterModelTable(
            name='configfile',
            table='config_file',
        ),
    ]
