# Generated by Django 3.1.1 on 2021-01-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0012_auto_20210122_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instancetype',
            table='instance_type',
        ),
        migrations.AlterModelTable(
            name='linetype',
            table='line_type',
        ),
        migrations.AlterModelTable(
            name='translationblock',
            table='translation_block',
        ),
        migrations.AlterModelTable(
            name='translationfile',
            table='translation_file',
        ),
        migrations.AlterModelTable(
            name='translationline',
            table='translation_line',
        ),
    ]
